probe error out to file to see stop/start states
Version 2.6.0b probe error out to file for examination to detect stopping/starting states

diff --git a/src/ha-cluster/metadataserver.in b/src/ha-cluster/metadataserver.in
--- a/src/ha-cluster/metadataserver.in
+++ b/src/ha-cluster/metadataserver.in
@@ -352,7 +352,39 @@ lizardfs_probe() {
 	else
 		host=$matocl_host
 	fi
-	lizardfs-admin metadataserver-status --porcelain "${host}" "$matocl_port"
+# Send any errors to /tmp/lizardfs_probe for later examination
+	results=`lizardfs-admin metadataserver-status --porcelain "${host}" "$matocl_port" 2>|/tmp/lizardfs_probe`
+# Capture the exit code from this probe command, 0 exited cleanly, but....
+        ret=$?
+## Prior to capturing the results= of the lizardfs-admin metadataserver-status command it is possible to exit(0) while stopping
+## Error: Can't connect to 127.0.0.1:9421: ENOTCONN (Transport endpoint is not connected)  #### exit(0) While Stopping
+## Error: Can't read data from socket: timeout                                             #### exit(1) While Starting during newly downloaded metadata from master server
+        if [ $ret -eq 0 ] ; then
+# Exit was 0, but if an error included ENOTCONN then the shadow service is stoping, return a unique response
+## metadataserver[000]: DEBUG: running in shadow mode, latest metadata is not available: 3 < 1098959141
+## After capturing the results= of the lizardfs-admin metadataserver-status command, this state should never be encountered
+		if [ `grep -c ENOTCONN /tmp/lizardfs_probe` -gt 0 ] ; then
+			echo -e "shadow\tstopping\t3"
+		else
+# Exit was 0, no error so return the normal probe results
+## metadataserver[000]: DEBUG: running in shadow mode, have latest metadata: 1098959141 ## If the cluster is idle and there have been no changes.
+## metadataserver[000]: DEBUG: running in shadow mode, no metadata # If the cluster is active and the metadata version has increased.
+			echo "$results"
+		fi
+# Exit was 1, so we might be stopping or starting and processing newly aquired metadata from the master server.
+	else
+# Error output included ENOTCONN so the shadow service is stoping, return a unique response
+## metadataserver[000]: DEBUG: running in shadow mode, latest metadata is not available: 2 < 1098959141
+		if [ `grep -c ENOTCONN /tmp/lizardfs_probe` -gt 0 ] ; then
+			echo -e "shadow\tstopping\t2"
+# Check for recent file activity and return a unique response if there is file activity in the last minute.
+## metadataserver[000]: DEBUG: running in shadow mode, latest metadata is not available: 1 < 1098959141
+# Verified that is `killall mfsmaster` this "unexpected output from lizardfs-admin:" will at least keep corosync from acting until the shutdown exits cleanly.
+		elif [ ! -z 'find ${data_dir}/ -mmin -1' ] ; then
+			echo -e "shadow\tconnected\t1"
+		fi
+	fi
+# else we returned nothing? shrugs
 }
 
 update_master_score() {
@@ -386,17 +418,8 @@ lizardfs_master_monitor() {
 		# master
 		probe_result=$(lizardfs_probe)
 		if [ $? -ne 0 ] ; then
-# Failed to query via port.
-# But we might still be starting or stopping...
-# Check if we have a lock file before deciding our state
-		if [ -e "$master_lock" ] ; then
-			ocf_log debug "LizardFS metadata server might be starting or stopping."
-			update_master_score ${score_shadow_no_metadata}
-			return $OCF_RUNNING_MASTER
-		else
 			ocf_log err "failed to query LizardFS master status"
 			return $OCF_ERR_GENERIC
-		fi
 		fi
 		local personality=$(echo "$probe_result" | cut -f1)
 		local connection=$(echo "$probe_result" | cut -f2)
@@ -409,7 +432,7 @@ lizardfs_master_monitor() {
 				set_metadata_version "${metadata_version}"
 				return $OCF_RUNNING_MASTER
 			;;
-			shadow/connected|shadow/disconnected)
+			shadow/connected|shadow/disconnected|shadow/stopping)
 				local cluster_metadata_version=$(get_metadata_version)
 				if [[ ( $? != 0 ) || ( ${cluster_metadata_version} == "" ) ]] ; then
 					ocf_log error "Failed to obtain metadata version from cluster."
@@ -558,7 +581,7 @@ case "$1" in
 	reload)   lizardfs_master_reload;;
 	promote)  lizardfs_master_promote;;
 	demote)   lizardfs_master_demote;;
-	#notify)   lizardfs_master_notify;;
+	# notify)   lizardfs_master_notify;;
 	# We have already validated by now
 	validate-all) ;;
 	*)        usage; exit $OCF_ERR_UNIMPLEMENTED;;
